
/* Automatically generated by './build/bin/build-entry.js' */
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Row from '../packages/row/index.js';
import Backtop from '../packages/backtop/index.js';
import locale from 'element-ui/src/locale';

const components = [Button,
ButtonGroup,
Scrollbar,
Row,
Backtop];

const install = function(Vue, opts = {}) {
	locale.use(opts.locale);

	components.forEach(component => {
		Vue.component(component.name, component);
	});

	Vue.prototype.$ELEMENT = {
		size: opts.size || '',
		zIndex: opts.zIndex || 2000
	};

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  	install(window.Vue);
}

export default {
	version: '2.13.2',
	locale: locale.use,
	i18n: locale.i18n,
	install,
	  Button,
  ButtonGroup,
  Scrollbar,
  Row,
  Backtop
};
